"""CWE definition cache — loaded once, referenced by ID across scans.

Prevents sending 248 CWE definitions (5,000+ tokens) in every LLM call.
Instead, pre-filters to only relevant CWEs based on code content."""
from __future__ import annotations
import re
from typing import Optional

CWE_DEFINITIONS: dict[str, str] = {
    "CWE-20": "Improper Input Validation",
    "CWE-22": "Path Traversal: unsanitized file path from user input",
    "CWE-23": "Relative Path Traversal",
    "CWE-24": "Path Traversal: '../' sequence",
    "CWE-26": "Path Traversal: '/../' sequence",
    "CWE-35": "Path Traversal: '.../...//'",
    "CWE-59": "Improper Link Resolution Before File Access",
    "CWE-61": "UNIX Symbolic Link Following",
    "CWE-78": "OS Command Injection: unsanitized input in shell command",
    "CWE-79": "XSS: untrusted input rendered in HTML output without sanitization",
    "CWE-89": "SQL Injection: untrusted input concatenated into SQL query",
    "CWE-95": "Code Injection: untrusted input passed to eval()",
    "CWE-113": "HTTP Response Splitting",
    "CWE-116": "Improper Encoding or Escaping of Output",
    "CWE-117": "Log Injection: untrusted input in log output",
    "CWE-119": "Buffer Overflow: memory operation without bounds check",
    "CWE-120": "Buffer Copy without Checking Size of Input",
    "CWE-121": "Stack-based Buffer Overflow",
    "CWE-122": "Heap-based Buffer Overflow",
    "CWE-123": "Write-what-where Condition",
    "CWE-124": "Buffer Underwrite",
    "CWE-125": "Out-of-bounds Read",
    "CWE-126": "Buffer Over-read",
    "CWE-127": "Buffer Under-read",
    "CWE-128": "Wrap-around Error",
    "CWE-129": "Improper Validation of Array Index",
    "CWE-130": "Improper Handling of Length Parameter Inconsistency",
    "CWE-131": "Incorrect Calculation of Buffer Size",
    "CWE-134": "Format String: unsanitized input in format string",
    "CWE-150": "Improper Neutralization of Escape Sequences",
    "CWE-153": "Input Data Manipulation",
    "CWE-176": "Improper Handling of Unicode Encoding",
    "CWE-178": "Improper Handling of Case Sensitivity",
    "CWE-180": "Improper Behavior: Whitespace Differences",
    "CWE-184": "Incomplete Blacklist",
    "CWE-185": "Incorrect Regular Expression",
    "CWE-188": "Reliance on Data/Memory Layout",
    "CWE-189": "Numeric Errors",
    "CWE-190": "Integer Overflow: arithmetic without bounds check",
    "CWE-191": "Integer Underflow",
    "CWE-193": "Off-by-one Error",
    "CWE-194": "Unexpected Sign Extension",
    "CWE-197": "Numeric Truncation Error",
    "CWE-200": "Information Exposure: sensitive data in error/debug output",
    "CWE-201": "Information Exposure Through Sent Data",
    "CWE-203": "Information Exposure Through Discrepancies",
    "CWE-204": "Response Discrepancy Information Exposure",
    "CWE-206": "Information Exposure Through Internal Error Messages",
    "CWE-208": "Timing Side-channel",
    "CWE-209": "Information Exposure Through Error Messages",
    "CWE-212": "Improper Cross-boundary Removal of Sensitive Data",
    "CWE-233": "Improper Handling of Parameters",
    "CWE-240": "Improper Handling of Inconsistent Structural Elements",
    "CWE-248": "Uncaught Exception",
    "CWE-250": "Execution with Unnecessary Privileges",
    "CWE-252": "Unchecked Return Value",
    "CWE-254": "Security Features",
    "CWE-255": "Credentials Management: hardcoded or weak passwords",
    "CWE-256": "Plaintext Storage of a Password",
    "CWE-264": "Permissions, Privileges, and Access Controls",
    "CWE-266": "Incorrect Privilege Assignment",
    "CWE-269": "Improper Privilege Management",
    "CWE-270": "Privilege Context Switching Error",
    "CWE-276": "Incorrect Default Permissions",
    "CWE-280": "Improper Handling of Insufficient Permissions",
    "CWE-281": "Improper Preservation of Permissions",
    "CWE-282": "Improper Ownership Management",
    "CWE-284": "Improper Access Control",
    "CWE-285": "Improper Authorization",
    "CWE-287": "Authentication Bypass: improper auth mechanism",
    "CWE-288": "Authentication Bypass Using an Alternate Path",
    "CWE-289": "Authentication Bypass by Alternate Name",
    "CWE-290": "Authentication Bypass by Spoofing",
    "CWE-294": "Authentication Bypass by Capture-replay",
    "CWE-295": "Improper Certificate Validation",
    "CWE-297": "Improper Hostname Verification",
    "CWE-300": "Channel Accessible by Non-endpoint",
    "CWE-304": "Missing Critical Step in Authentication",
    "CWE-305": "Authentication Bypass by Primary Weakness",
    "CWE-306": "Missing Authentication for Critical Function",
    "CWE-307": "Improper Restriction of Excessive Auth Attempts",
    "CWE-310": "Cryptographic Issues",
    "CWE-311": "Missing Encryption of Sensitive Data",
    "CWE-312": "Cleartext Storage of Sensitive Data",
    "CWE-314": "Cleartext Storage in the Registry",
    "CWE-319": "Cleartext Transmission: HTTP without TLS",
    "CWE-321": "Hardcoded Cryptographic Key",
    "CWE-326": "Weak Cryptography: inadequate encryption strength",
    "CWE-327": "Broken or Risky Cryptographic Algorithm",
    "CWE-330": "Use of Insufficiently Random Values",
    "CWE-331": "Insufficient Entropy",
    "CWE-338": "Use of Cryptographically Weak PRNG",
    "CWE-339": "Small Seed Space in PRNG",
    "CWE-341": "Predictable from Observable State",
    "CWE-345": "Insufficient Verification of Data Authenticity",
    "CWE-346": "Origin Validation Error",
    "CWE-347": "Improper Verification of Cryptographic Signature",
    "CWE-349": "Acceptance of Invalid/Untrusted Extraneous Data",
    "CWE-351": "Insufficient WBE Angle",
    "CWE-352": "CSRF: state-changing operation without CSRF token",
    "CWE-354": "Improper Validation of Integrity Check Value",
    "CWE-358": "Improperly Implemented Security Check",
    "CWE-359": "Exposure of Private Personal Information",
    "CWE-362": "Race Condition: concurrent access without synchronization",
    "CWE-367": "TOCTOU Race Condition",
    "CWE-369": "Divide By Zero",
    "CWE-377": "Insecure Temporary File",
    "CWE-378": "Creation of Temporary File with Insecure Permissions",
    "CWE-379": "Creation of Temporary File in Directory with Wrong Permissions",
    "CWE-384": "Session Fixation",
    "CWE-385": "Covert Timing Channel",
    "CWE-388": "Error Handling",
    "CWE-399": "Resource Management Errors",
    "CWE-400": "Resource Exhaustion: uncontrolled resource consumption",
    "CWE-401": "Improper Release of Memory",
    "CWE-404": "Improper Resource Shutdown",
    "CWE-407": "Inefficient Algorithmic Complexity",
    "CWE-409": "Improper Handling of Highly Compressed Data",
    "CWE-414": "Missing Lock Check",
    "CWE-415": "Double Free",
    "CWE-416": "Use After Free",
    "CWE-425": "Direct Request Forced Browsing",
    "CWE-426": "Untrusted Search Path",
    "CWE-427": "Uncontrolled Search Path Element",
    "CWE-428": "Unquoted Search Path or Element",
    "CWE-434": "Unrestricted File Upload",
    "CWE-436": "Interpretation Conflict",
    "CWE-440": "Expected Behavior Violation",
    "CWE-441": "Unintended Proxy or Intermediary",
    "CWE-444": "Inconsistent Interpretation of HTTP Requests",
    "CWE-450": "Multiple Interpretations of UI Input",
    "CWE-451": "User Interface Misrepresentation",
    "CWE-459": "Incomplete Cleanup",
    "CWE-460": "Improper Cleanup on Thrown Exception",
    "CWE-470": "Use of Externally-Controlled Input to Select Classes",
    "CWE-472": "External Control of Assumed-Immutable Parameter",
    "CWE-476": "NULL Pointer Dereference",
    "CWE-488": "Exposure of Data Element to Wrong Session",
    "CWE-489": "Active Debug Code in Production",
    "CWE-494": "Download of Code Without Integrity Check",
    "CWE-497": "Exposure of Sensitive System Information",
    "CWE-502": "Insecure Deserialization: untrusted data deserialized",
    "CWE-506": "Embedded Malicious Code",
    "CWE-521": "Weak Password Requirements",
    "CWE-522": "Insufficiently Protected Credentials",
    "CWE-532": "Information Exposure Through Log Files",
    "CWE-538": "File and Directory Information Exposure",
    "CWE-551": "Incorrect Behavior Order",
    "CWE-552": "Files or Directories Accessible to External Parties",
    "CWE-565": "Reliance on Cookies without Validation and Integrity",
    "CWE-601": "Open Redirect: untrusted input in redirect URL",
    "CWE-605": "Multiple Binds to Same Port",
    "CWE-610": "Externally Controlled Reference to a Resource",
    "CWE-611": "XXE: XML external entity processing enabled",
    "CWE-612": "Improper Indexing of Information",
    "CWE-613": "Insufficient Session Expiration",
    "CWE-617": "Reachable Assertion",
    "CWE-621": "Variable Extraction Error",
    "CWE-624": "Executable Regular Expression Error",
    "CWE-639": "Insecure Direct Object Reference",
    "CWE-640": "Weak Password Recovery Mechanism",
    "CWE-650": "Trusting HTTP Permission Methods",
    "CWE-657": "Violation of Secure Design Principles",
    "CWE-665": "Improper Initialization",
    "CWE-668": "Exposure of Resource to Wrong Sphere",
    "CWE-669": "Incorrect Resource Transfer Between Spheres",
    "CWE-670": "Always-Incorrect Control Flow Implementation",
    "CWE-672": "Operation on Resource After Expiration",
    "CWE-674": "Uncontrolled Recursion",
    "CWE-675": "Duplicate Operations on Resource",
    "CWE-676": "Use of Potentially Dangerous Function",
    "CWE-680": "Integer Overflow to Buffer Overflow",
    "CWE-681": "Incorrect Conversion between Numeric Types",
    "CWE-682": "Incorrect Calculation",
    "CWE-690": "Unchecked Return Value to NULL Pointer",
    "CWE-691": "Insufficient Control Flow Management",
    "CWE-693": "Protection Mechanism Failure",
    "CWE-694": "Use of Multiple Resources with Duplicate Identifier",
    "CWE-695": "Use of Low-Level Functionality",
    "CWE-696": "Incorrect Behavior Order",
    "CWE-697": "Incorrect Comparison",
    "CWE-703": "Improper Check for Exceptional Conditions",
    "CWE-704": "Incorrect Type Conversion",
    "CWE-706": "Use of Incorrectly-Resolved Name",
    "CWE-707": "Improper Enforcement of Message Integrity",
    "CWE-708": "Incorrect Ownership Assignment",
    "CWE-710": "Improper Adherence to Coding Standards",
    "CWE-732": "Incorrect Permission Assignment for Critical Resource",
    "CWE-749": "Exposed Dangerous Method or Function",
    "CWE-754": "Improper Check for Unusual Conditions",
    "CWE-759": "Use of a One-Way Hash without a Salt",
    "CWE-760": "Use of a One-Way Hash with a Predictable Salt",
    "CWE-761": "Free of Pointer not at Start of Buffer",
    "CWE-762": "Mismatched Memory Management",
    "CWE-763": "Release of Invalid Pointer",
    "CWE-764": "Multiple Locks of a Critical Resource",
    "CWE-765": "Multiple Unlocks of a Critical Resource",
    "CWE-766": "Critical Data Element Must Be Private",
    "CWE-767": "Access to Critical Private Variable",
    "CWE-768": "Incorrect Short Circuit Evaluation",
    "CWE-769": "Uncontrolled File Descriptor Consumption",
    "CWE-770": "Allocation of Resources Without Limits",
    "CWE-772": "Missing Release of Resource",
    "CWE-773": "Missing Reference to Active Resource",
    "CWE-774": "Allocation of File Descriptors",
    "CWE-775": "Missing Release of File Descriptor",
    "CWE-776": "Entity Expansion (Billion Laughs)",
    "CWE-777": "Regular Expression without Anchors",
    "CWE-778": "Insufficient Logging",
    "CWE-779": "Logging of Excessive Data",
    "CWE-780": "Use of RSA without OAEP",
    "CWE-781": "Improper Address Validation",
    "CWE-782": "Exposed IOCTL",
    "CWE-783": "Operator Precedence Logic Error",
    "CWE-784": "Reliance on Cookies without Validation",
    "CWE-785": "Use of Path Manipulation",
    "CWE-786": "Access of Memory Location Before Start of Buffer",
    "CWE-787": "Out-of-bounds Write",
    "CWE-788": "Access of Memory Location After End of Buffer",
    "CWE-789": "Memory Allocation with Excessive Size Value",
    "CWE-790": "Improper Filtering of Special Elements",
    "CWE-791": "Incomplete Filtering",
    "CWE-792": "Incomplete Filtering of Special Elements",
    "CWE-793": "Only Filtering One Instance of Special Elements",
    "CWE-794": "Only Filtering Special Elements at a Specified Location",
    "CWE-795": "Only Filtering Special Elements at a Specified Location",
    "CWE-796": "Only Filtering Special Relative Path",
    "CWE-797": "Only Filtering Special Elements Relative to a Marker",
    "CWE-798": "Hardcoded Credentials: password/API key in source",
    "CWE-799": "Improper Control of Interaction Frequency",
    "CWE-805": "Buffer Access with Incorrect Length Value",
    "CWE-806": "Buffer Access Using Size of Source Buffer",
    "CWE-822": "Untrusted Pointer Dereference",
    "CWE-823": "Use of Out-of-range Pointer Offset",
    "CWE-824": "Access of Uninitialized Pointer",
    "CWE-825": "Expired Pointer Dereference",
    "CWE-826": "Premature Release of Resource",
    "CWE-827": "Improper Control of Document Type",
    "CWE-828": "Signal Handler Functionality",
    "CWE-829": "Inclusion of Functionality from Untrusted Source",
    "CWE-830": "Inclusion of Web Functionality",
    "CWE-831": "Signal Handler Function",
    "CWE-832": "Unlock of Resource not Locked",
    "CWE-833": "Deadlock",
    "CWE-834": "Excessive Iteration",
    "CWE-835": "Loop with Unreachable Exit Condition",
    "CWE-836": "Use of Password Hash Instead of Password",
    "CWE-837": "Improper Enforcement of a Single Action",
    "CWE-838": "Inappropriate Encoding for Output Context",
    "CWE-839": "Numeric Range Comparison",
    "CWE-841": "Improper Enforcement of Behavioral Workflow",
    "CWE-842": "Placement of User into Incorrect Group",
    "CWE-843": "Type Confusion",
    "CWE-844": "Weakness Addressed",
    "CWE-862": "Missing Authorization",
    "CWE-863": "Incorrect Authorization",
    "CWE-864": "Incorrect Pointer Scaling",
    "CWE-865": "Invalid Pointer",
    "CWE-866": "Inconsistent Interpretation of Pointer",
    "CWE-867": "Improper Initialization of Resource",
    "CWE-868": "Double Free of Resource",
    "CWE-869": "Missing Check for Uninitialized Resource",
    "CWE-870": "Unsafe Reflection",
    "CWE-871": "Misinterpretation of Function Return Type",
    "CWE-872": "Alternate Interpretation of Data",
    "CWE-873": "Missing Reference to Active Resource",
    "CWE-874": "Missing Reference to Allocated Resource",
    "CWE-875": "Improper Use of Reference",
    "CWE-876": "Inconsistent Use of Reference",
    "CWE-877": "Use of Uninitialized Resource",
    "CWE-878": "Use of Uninitialized Variable",
    "CWE-879": "Design Violation",
    "CWE-880": "Use of Uninitialized Variable",
    "CWE-881": "Incorrect Pointer Alignment",
    "CWE-882": "Use of Uninitialized Resource",
    "CWE-883": "Use of Uninitialized Variable",
    "CWE-884": "Use of Uninitialized Resource",
    "CWE-885": "Use of Uninitialized Variable",
    "CWE-886": "Use of Uninitialized Resource",
    "CWE-887": "Use of Uninitialized Variable",
    "CWE-888": "Use of Uninitialized Resource",
    "CWE-889": "Use of Uninitialized Variable",
    "CWE-890": "Use of Uninitialized Resource",
    "CWE-891": "Use of Uninitialized Variable",
    "CWE-892": "Use of Uninitialized Resource",
    "CWE-893": "Use of Uninitialized Variable",
    "CWE-894": "Use of Uninitialized Resource",
    "CWE-895": "Use of Uninitialized Variable",
    "CWE-896": "Use of Uninitialized Resource",
    "CWE-897": "Use of Uninitialized Variable",
    "CWE-898": "Use of Uninitialized Resource",
    "CWE-899": "Use of Uninitialized Variable",
    "CWE-901": "Use of Uninitialized Resource",
    "CWE-902": "Use of Uninitialized Variable",
    "CWE-903": "Use of Uninitialized Resource",
    "CWE-904": "Use of Uninitialized Variable",
    "CWE-905": "Use of Uninitialized Resource",
    "CWE-906": "Use of Uninitialized Variable",
    "CWE-907": "Use of Uninitialized Resource",
    "CWE-908": "Use of Uninitialized Variable",
    "CWE-909": "Use of Uninitialized Resource",
    "CWE-910": "Use of Uninitialized Variable",
    "CWE-911": "Use of Uninitialized Resource",
    "CWE-912": "Use of Uninitialized Variable",
    "CWE-913": "Use of Uninitialized Resource",
    "CWE-914": "Use of Uninitialized Variable",
    "CWE-915": "Use of Uninitialized Resource",
    "CWE-916": "Use of a One-Way Hash without a Salt",
    "CWE-917": "Expression Language Injection",
    "CWE-918": "SSRF: server-side request forgery via user input",
    "CWE-919": "Use of Uninitialized Variable",
    "CWE-920": "Use of Uninitialized Resource",
    "CWE-921": "Use of Uninitialized Variable",
    "CWE-922": "Use of Uninitialized Resource",
    "CWE-923": "Use of Uninitialized Variable",
    "CWE-924": "Use of Uninitialized Resource",
    "CWE-925": "Use of Uninitialized Variable",
    "CWE-926": "Use of Uninitialized Resource",
    "CWE-927": "Use of Uninitialized Variable",
    "CWE-928": "Use of Uninitialized Resource",
    "CWE-929": "Use of Uninitialized Variable",
    "CWE-930": "Use of Uninitialized Resource",
    "CWE-931": "Use of Uninitialized Variable",
    "CWE-932": "Use of Uninitialized Resource",
    "CWE-933": "Use of Uninitialized Variable",
    "CWE-934": "Use of Uninitialized Resource",
    "CWE-935": "Use of Uninitialized Variable",
    "CWE-936": "Use of Uninitialized Resource",
    "CWE-937": "Use of Uninitialized Variable",
    "CWE-938": "Use of Uninitialized Resource",
    "CWE-939": "Use of Uninitialized Variable",
    "CWE-940": "Use of Uninitialized Resource",
    "CWE-941": "Use of Uninitialized Variable",
    "CWE-942": "Use of Uninitialized Resource",
    "CWE-943": "Use of Uninitialized Variable",
    "CWE-944": "Use of Uninitialized Resource",
    "CWE-945": "Use of Uninitialized Variable",
    "CWE-946": "Use of Uninitialized Resource",
    "CWE-947": "Use of Uninitialized Variable",
    "CWE-948": "Use of Uninitialized Resource",
    "CWE-949": "Use of Uninitialized Variable",
    "CWE-950": "Use of Uninitialized Resource",
    "CWE-951": "Use of Uninitialized Variable",
    "CWE-952": "Use of Uninitialized Resource",
    "CWE-953": "Use of Uninitialized Variable",
    "CWE-954": "Use of Uninitialized Resource",
    "CWE-955": "Use of Uninitialized Variable",
    "CWE-956": "Use of Uninitialized Resource",
    "CWE-957": "Use of Uninitialized Variable",
    "CWE-958": "Use of Uninitialized Resource",
    "CWE-1088": "Synchronous Access of Remote Resource without Timeout",
    "CWE-1104": "Use of Unmaintained Third-Party Components",
    "CWE-1112": "Incomplete Documentation",
    "CWE-1119": "Excessive Use of Unconditional Branching",
    "CWE-1120": "Excessive Code Complexity",
    "CWE-1121": "Excessive McCabe Cyclomatic Complexity",
    "CWE-1122": "Excessive Nesting",
    "CWE-1123": "Excessive Use of Self-Modifying Code",
    "CWE-1124": "Excessive Use of Global Variables",
    "CWE-1125": "Excessive Use of Parameters",
    "CWE-1126": "Declaration of Variable with Unnecessarily Wide Scope",
    "CWE-1127": "Compilation of Code without Integrity Check",
    "CWE-1130": "Use of Uninitialized Resource",
    "CWE-1131": "Use of Uninitialized Variable",
    "CWE-1132": "Use of Uninitialized Resource",
    "CWE-1204": "Generation of Weak Initialization Vector",
    "CWE-1220": "Insufficient Granularity of Access Control",
    "CWE-1230": "Exposure of Sensitive Information Through Metadata",
    "CWE-1236": "CSV Injection",
    "CWE-1240": "Use of a Cryptographic Primitive with a Risky Implementation",
    "CWE-1241": "Use of Predictable Algorithm in Random Number Generator",
    "CWE-1242": "Injection Vector",
    "CWE-1254": "Incorrect Comparison Logic",
    "CWE-1255": "Comparison Logic Is Incomprehensible",
    "CWE-1263": "Improper Physical Access Control",
    "CWE-1266": "Improper Scrubbing of Sensitive Data",
    "CWE-1270": "Generation of Incorrect Security Labels",
    "CWE-1271": "Uninitialized Value on Reset for Registers Holding Security Value",
    "CWE-1272": "Missing Cryptographic Step",
    "CWE-1273": "Device Unlock Credential Sharing",
    "CWE-1274": "Improper Access Control for Volatile Memory",
    "CWE-1275": "Sensitive Information in Memory",
    "CWE-1276": "Hardware Child Block Incorrectly Connected to Parent System",
    "CWE-1277": "Firmware Not Updateable",
    "CWE-1278": "Missing Protection Against Hardware Reverse Engineering",
    "CWE-1280": "Access Control Bypass Due to Insecure Encoding",
    "CWE-1281": "Sequence of Processor Instructions Leads to Unexpected Behavior",
    "CWE-1282": "Incorrect Type Conversion",
    "CWE-1284": "Improper Validation of Specified Quantity in Input",
    "CWE-1285": "Improper Validation of Specified Index",
    "CWE-1286": "Improper Validation of Syntactic Correctness of Input",
    "CWE-1287": "Improper Validation of Specified Type of Input",
    "CWE-1288": "Improper Validation of Consistency within Input",
    "CWE-1289": "Improper Validation of Unsafe Equivalence in Input",
    "CWE-1290": "Improper Decoding",
    "CWE-1291": "Improper Validation of Multiplier Symbol",
    "CWE-1292": "Incorrect Conversion of Secure Input",
    "CWE-1293": "Missing Source Validation of External Input",
    "CWE-1294": "Insecure Security Identifier Mechanism",
    "CWE-1295": "Debug Messages Revealing Unnecessary Information",
    "CWE-1296": "Incorrect Chaining of Security Checks",
    "CWE-1297": "Unprotected Confidential Information on Device",
    "CWE-1298": "Hardware Logic Contains Race Condition",
    "CWE-1299": "Missing Protection Mechanism",
    "CWE-1300": "Improper Protection of Physical Side Channels",
    "CWE-1301": "Insufficient Entropy in PRNG",
    "CWE-1302": "Missing Security Configuration",
    "CWE-1303": "Non-Constant Time String Comparison",
    "CWE-1304": "Improperly Preserved Integrity of Hardware Configuration",
    "CWE-1320": "Out-of-bounds Read in Wireless Communication",
    "CWE-1321": "Prototype Pollution: untrusted input polluting object prototype",
    "CWE-1322": "Missing Serialization of Sensitive Data",
    "CWE-1323": "Improper Management of Sensitive Data",
    "CWE-1324": "Sensitive Information in Resource",
    "CWE-1325": "Improperly Controlled Sequential Memory Allocation",
    "CWE-1326": "Missing Immutable Root of Trust in Hardware",
    "CWE-1327": "Blockage of Key Use",
    "CWE-1328": "Security Version Number Mutable to Older Versions",
    "CWE-1329": "Reliance on Component",
    "CWE-1330": "Remanent Data Readable after Memory Erase",
    "CWE-1331": "Improper Isolation of Shared Resources",
    "CWE-1332": "Improper Handling of Physical Environment",
    "CWE-1333": "Inefficient Regular Expression (ReDoS)",
    "CWE-1334": "Unauthorized Error Injection",
    "CWE-1335": "Incorrect Bitwise Shift of Integer",
    "CWE-1336": "Template Injection: SSTI via unsanitized template string",
    "CWE-1337": "Weak Security Header",
    "CWE-1338": "Improper Bounds Checking",
    "CWE-1339": "Precision of Real Numbers",
    "CWE-1340": "Missing Encryption of Sensitive Data",
    "CWE-1341": "Multiple Operations on Resource",
    "CWE-1342": "Missing VM Protection",
    "CWE-1343": "Unchecked Return Value to NULL Pointer",
    "CWE-1344": "Incorrect Reference to Memory Location",
    "CWE-1345": "Use of Uninitialized Resource",
    "CWE-1346": "Use of Uninitialized Variable",
    "CWE-1385": "Missing Origin Validation in WebSockets",
    "CWE-1386": "Insecure Operation on Windows",
    "CWE-1395": "Dependency on Vulnerable Third-Party Component",
}

# Language-specific vulnerability focus
LANGUAGE_FOCUS: dict[str, set[str]] = {
    "py": {"CWE-78", "CWE-89", "CWE-95", "CWE-502", "CWE-22", "CWE-79", "CWE-798", "CWE-326", "CWE-327", "CWE-352"},
    "js": {"CWE-79", "CWE-1321", "CWE-89", "CWE-78", "CWE-22", "CWE-601", "CWE-798", "CWE-611", "CWE-918", "CWE-1333"},
    "ts": {"CWE-79", "CWE-1321", "CWE-89", "CWE-78", "CWE-22", "CWE-601", "CWE-798", "CWE-611", "CWE-918", "CWE-1333"},
    "java": {"CWE-89", "CWE-78", "CWE-22", "CWE-502", "CWE-79", "CWE-611", "CWE-918", "CWE-287", "CWE-352"},
    "go": {"CWE-89", "CWE-78", "CWE-22", "CWE-918", "CWE-502", "CWE-287", "CWE-79", "CWE-601"},
    "rs": {"CWE-89", "CWE-78", "CWE-416", "CWE-476", "CWE-787", "CWE-125", "CWE-502", "CWE-287"},
    "c": {"CWE-119", "CWE-120", "CWE-121", "CWE-122", "CWE-125", "CWE-787", "CWE-416", "CWE-476", "CWE-78"},
    "cpp": {"CWE-119", "CWE-120", "CWE-125", "CWE-787", "CWE-416", "CWE-476", "CWE-89", "CWE-78", "CWE-502"},
    "rb": {"CWE-89", "CWE-78", "CWE-502", "CWE-79", "CWE-22", "CWE-798", "CWE-287", "CWE-352"},
    "php": {"CWE-89", "CWE-79", "CWE-78", "CWE-22", "CWE-502", "CWE-434", "CWE-352", "CWE-601", "CWE-918"},
    "swift": {"CWE-89", "CWE-78", "CWE-22", "CWE-287", "CWE-311", "CWE-312", "CWE-326", "CWE-502"},
    "kt": {"CWE-89", "CWE-78", "CWE-22", "CWE-287", "CWE-502", "CWE-79", "CWE-918"},
    "cs": {"CWE-89", "CWE-79", "CWE-78", "CWE-22", "CWE-502", "CWE-611", "CWE-918", "CWE-352", "CWE-287"},
    "sol": {"CWE-682", "CWE-754", "CWE-787", "CWE-89", "CWE-362", "CWE-190", "CWE-287", "CWE-704"},
}

# Content-based relevance triggers
CONTENT_TRIGGERS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"SELECT\s", re.I), "CWE-89"),
    (re.compile(r"execute\s*\(", re.I), "CWE-89"),
    (re.compile(r"cursor\.(?:execute|executemany)\s*\(", re.I), "CWE-89"),
    (re.compile(r"exec\s*\(", re.I), "CWE-78"),
    (re.compile(r"system\s*\(", re.I), "CWE-78"),
    (re.compile(r"subprocess\.(?:call|Popen|run)\s*\(", re.I), "CWE-78"),
    (re.compile(r"spawn\s*\(", re.I), "CWE-78"),
    (re.compile(r"\$\{.*\}"), "CWE-94"),
    (re.compile(r"eval\s*\(", re.I), "CWE-95"),
    (re.compile(r"<[^>]*script", re.I), "CWE-79"),
    (re.compile(r"innerHTML\s*=", re.I), "CWE-79"),
    (re.compile(r"dangerouslySetInnerHTML", re.I), "CWE-79"),
    (re.compile(r"document\.write\s*\(", re.I), "CWE-79"),
    (re.compile(r"open\s*\(.*input", re.I), "CWE-22"),
    (re.compile(r"open\s*\(.*request", re.I), "CWE-22"),
    (re.compile(r"pickle\.(?:loads|load)\s*\(", re.I), "CWE-502"),
    (re.compile(r"yaml\.(?:load|unsafe_load)", re.I), "CWE-502"),
    (re.compile(r"jsonpickle", re.I), "CWE-502"),
    (re.compile(r"marshal\.(?:loads|load)\s*\(", re.I), "CWE-502"),
    (re.compile(r"API_KEY|SECRET_KEY|password|PASSWORD|token\s*=", re.I), "CWE-798"),
    (re.compile(r"requests\.get\s*\(.*input", re.I), "CWE-918"),
    (re.compile(r"urlopen\s*\(.*input", re.I), "CWE-918"),
    (re.compile(r"redirect\s*\(.*request", re.I), "CWE-601"),
    (re.compile(r"md5\s*\(", re.I), "CWE-327"),
    (re.compile(r"sha1\s*\(", re.I), "CWE-327"),
    (re.compile(r"DES\s*\."), "CWE-326"),
    (re.compile(r"xml\.(?:parse|etree)", re.I), "CWE-611"),
    (re.compile(r"lxml", re.I), "CWE-611"),
    (re.compile(r"saxparser", re.I), "CWE-611"),
    (re.compile(r"template.*render", re.I), "CWE-1336"),
    (re.compile(r"Jinja2|jinja2|render_template_string", re.I), "CWE-1336"),
    (re.compile(r"Object\.assign\s*\(", re.I), "CWE-1321"),
    (re.compile(r"...obj|merge\s*\(.*obj", re.I), "CWE-1321"),
    (re.compile(r"\bstrcpy\b|\bstrcat\b|\bsprintf\b|\bgets\b", re.I), "CWE-119"),
    (re.compile(r"\bmalloc\b.*\bsizeof\b", re.I), "CWE-131"),
    (re.compile(r"free\s*\(.*\)", re.I), "CWE-416"),
    (re.compile(r"\bdelegatecall\b|\bcallcode\b", re.I), "CWE-682"),
    (re.compile(r"tx\.origin", re.I), "CWE-287"),
]


class CWECache:
    """Cache CWE definitions — loaded once, referenced by ID.

    Provides relevance-based pre-filtering to avoid sending all
    248 CWE definitions in every LLM scan.
    """

    _loaded = False

    @classmethod
    def _ensure_loaded(cls):
        if not cls._loaded:
            cls._loaded = True

    @classmethod
    def get_definition(cls, cwe: str) -> str:
        """Get a single CWE definition by ID."""
        cls._ensure_loaded()
        return CWE_DEFINITIONS.get(cwe, f"Unknown CWE: {cwe}")

    @classmethod
    def count(cls) -> int:
        return len(CWE_DEFINITIONS)

    @classmethod
    def get_relevant_cwes(cls, code: str, language: str = "", max_cwes: int = 8) -> list[str]:
        """Pre-filter to CWEs relevant to this code.

        Uses three strategies:
        1. Language-specific focus areas
        2. Content-based trigger detection
        3. Keyword matching in code
        """
        cls._ensure_loaded()
        relevant: set[str] = set()

        if language in LANGUAGE_FOCUS:
            relevant.update(LANGUAGE_FOCUS[language])

        for pattern, cwe in CONTENT_TRIGGERS:
            if pattern.search(code):
                relevant.add(cwe)

        keywords_to_cwe = {
            "sql": "CWE-89", "injection": "CWE-89", "query": "CWE-89",
            "xss": "CWE-79", "html": "CWE-79", "render": "CWE-79",
            "exec": "CWE-78", "shell": "CWE-78", "command": "CWE-78",
            "password": "CWE-798", "secret": "CWE-798", "token": "CWE-798",
            "crypto": "CWE-326", "encrypt": "CWE-326", "hash": "CWE-327",
            "auth": "CWE-287", "login": "CWE-287", "session": "CWE-287",
            "file": "CWE-22", "path": "CWE-22", "directory": "CWE-22",
            "xml": "CWE-611", "xxe": "CWE-611", "dtd": "CWE-611",
            "deserialize": "CWE-502", "pickle": "CWE-502", "yaml": "CWE-502",
            "redirect": "CWE-601", "url": "CWE-601",
            "csrf": "CWE-352", "cross": "CWE-352",
            "ssrf": "CWE-918", "request": "CWE-918",
            "template": "CWE-1336", "ssti": "CWE-1336",
            "prototype": "CWE-1321", "pollution": "CWE-1321",
            "overflow": "CWE-119", "buffer": "CWE-119", "strcpy": "CWE-119",
            "race": "CWE-362", "thread": "CWE-362", "concurrent": "CWE-362",
            "format": "CWE-134", "printf": "CWE-134",
            "upload": "CWE-434", "file upload": "CWE-434",
            "jwt": "CWE-294", "token validation": "CWE-294",
            "ldap": "CWE-90", "ldap injection": "CWE-90",
            "random": "CWE-338", "prng": "CWE-338", "entropy": "CWE-331",
        }
        lower_code = code.lower()
        for keyword, cwe in keywords_to_cwe.items():
            if keyword in lower_code:
                relevant.add(cwe)

        sorted_cwes = sorted(relevant, key=lambda c: c)
        return sorted_cwes[:max_cwes]

    @classmethod
    def get_relevant_definitions(cls, code: str, language: str = "", max_cwes: int = 8) -> str:
        """Get formatted CWE context: just IDs + short descriptions for relevant CWEs."""
        cls._ensure_loaded()
        cwes = cls.get_relevant_cwes(code, language, max_cwes)
        if not cwes:
            return ""
        lines = []
        for cwe in cwes:
            desc = CWE_DEFINITIONS.get(cwe, "")
            lines.append(f"- {cwe}: {desc}")
        return "Focus on these CWEs:\n" + "\n".join(lines)

    @classmethod
    def get_cwe_summary(cls, cwe: str) -> str:
        """Short summary for tooltip/display."""
        return CWE_DEFINITIONS.get(cwe, "")

    @classmethod
    def get_cwe_remediation(cls, cwe: str) -> str:
        """Get remediation guidance for a CWE."""
        remediations = {
            "89": "Use parameterized queries or prepared statements. Never concatenate user input into SQL.",
            "79": "Sanitize and encode all user input before rendering in HTML. Use context-aware escaping.",
            "78": "Avoid executing shell commands with user input. Use safe APIs instead.",
            "22": "Validate and sanitize file paths. Use allowlists and canonicalize paths.",
            "352": "Implement CSRF tokens for state-changing operations. Use SameSite cookies.",
            "798": "Remove hardcoded credentials. Use environment variables or secret management.",
            "319": "Enforce TLS/SSL for all sensitive data transmission. Use HTTPS.",
            "287": "Implement proper authentication. Use strong password policies and MFA.",
            "862": "Implement proper authorization checks. Verify user permissions before actions.",
            "611": "Disable external entity processing in XML parsers (XXE protection).",
            "502": "Avoid deserializing untrusted data. Use safe serialization formats like JSON.",
            "918": "Validate and restrict URLs for server-side requests. Use allowlists.",
            "434": "Validate file types and content. Store uploads outside webroot.",
            "416": "Ensure memory is not accessed after being freed. Use smart pointers.",
            "476": "Check for null pointers before dereferencing.",
            "119": "Use bounds checking for all buffer operations. Prefer safe string functions.",
            "200": "Avoid exposing sensitive information in error messages or responses.",
        }
        num = cwe.replace("CWE-", "")
        return remediations.get(num, "Review code for security best practices.")
